export { AuthGuard } from './components/AuthGuard'
export { useAuthStore } from './store'
export { authApi } from './api'
export { default as LoginPage } from './pages/LoginPage/LoginPage'
export { default as RegisterPage } from './pages/RegisterPage/RegisterPage'
export { default as OAuthCallbackPage } from './pages/OAuthCallbackPage/OAuthCallbackPage'
export type { User, OAuthProvider, AuthResponse, AuthConfig } from './types'
